seed: 0


batch_size: 512
epochs: 80
eval_every_n_epochs: 1
fine_tune_from: None
log_every_n_steps: 50
weight_decay: 10e-6
fp16_precision: False
log_dir: "./results/resnet18_gpu2_bs128"

gpu: "0 1"

model:
  out_dim: 256
  base_model: "resnet18"

data_loader:
  dataset: "tinyimg"
  data_path: "../data/tiny-imagenet-200"
  supervised: False
  num_workers: 0
  distributed: True
  
loss:
  temperature: 0.5
  use_cosine_similarity: True
